## Numpy
파이썬의 고성능 과학 처리 패키지  
Matrix와 Vector와 같은 array연산의 사실상 표준  
하나의 타입만 배열에 넣을 수 있다.  

* 특징  
일반 list에 비해 빠르고, 메모리를 효율적으로 사용한다.  
반복문 없이 데이터 배열에 대한 처리를 지원함  
선형대수와 관련된 다양한 기능을 제공함  
C, C++ 등의 언어와 통합 가능  

In [2]:
# de facto standard
import numpy as np

### 1. ndarray(Numpy Dimensional Array)  

np.array 함수를 이용해서 배열을 생성한다. 

In [3]:
a = np.array([1,4,5,8],float)
print(a)

[1. 4. 5. 8.]


In [6]:
a[3], a.dtype, a.shape

(8.0, dtype('float64'), (4,))

### 2. Array shape

In [ ]:
# 1차원 - vector

a = np.array([1,4,5,8],float)


In [8]:
# 2차원 - matrix
m = list([[1,4],[5,8]])
b = np.array(m, float)
print(b)

[[1. 4.]
 [5. 8.]]


In [10]:
# 3차원 - tensor
t = [[[1,4],[5,8]],[[11,14],[15,18]]]
c = np.array(t,float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [11]:
# 각각의 shape살펴보기

a.shape, b.shape, c.shape

((4,), (2, 2), (2, 2, 2))

In [16]:
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [21]:
# size - element(원소)의 개수

a.size, b.size, c.size

(4, 4, 8)

In [23]:
# data type(dtype)

c = np.array(t,dtype =np.float32)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]], dtype=float32)

### 3. reshape 
size는 동일 - element의 개수는 동일하다

In [28]:
c.reshape(2,4).shape

(2, 4)

In [26]:
c.reshape(2,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [27]:
c.reshape(8,)

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

* wild character -1의 사용  
(-1,4)로 두면 뒤에 맞추어서 앞의 -1의 숫자가 결정이 된다.

In [29]:
c.reshape(-1,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

### 4.flatten
1차원으로 변환

In [31]:
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

### 5. Indexing and Slicing

In [33]:
a = np.arange(6)        # a = np.array(range(6))와 동일하다.
a

array([0, 1, 2, 3, 4, 5])

In [34]:
# 만들어서 2차원으로 한방에 
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
a[0][1], a[0,1]     # numpy 에서는 [0,1]처럼 줄여쓸 수 있다. 

(1, 1)

numpy는 2차원도 슬라이싱이 가능하다.

In [39]:
a[:,:2]

array([[0, 1],
       [3, 4]])

* 연습

In [40]:
b = np.arange(16).reshape(-1,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
# 5,6,9,10
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [42]:
# 0,1,4,5,8,9
b[:3,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [47]:
# 세번째 열 까지는 X, 마지막 열은 Y
X, Y = b[:,:-1], b[:,-1]

X.shape, Y.shape

((4, 3), (4,))

### 6. Creation

In [48]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

그냥 range에서는 실수를 소수점으로 쓸 수 없으나 넘파이에서는 가능하다. 

In [50]:
np.arange(0,1.1,0.1)    

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

리스트로 만들기도 가능  
-> 0.3, 0.6, 0.7의 경우 : 실수는 우리가 원하는 수를 정확하게 표시할 수 없다. 

In [53]:
np.arange(0,1.1,0.1).tolist()

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [55]:
np.arange(0,1.1,0.1).tolist()[3] == 0.3

False

In [54]:
np.arange(0,1.1,0.1).tolist()[2] == 0.2

True

그래서 실수인 경우에는 하단과 같이 해야함.  
값에서 빼서 10의 -8승보다 작느냐(차이가 아주 작느냐) 라고 물어보는게 맞고, 그렇게 하면 True가 나온다.

In [57]:
np.abs(np.arange(0,1.1,0.1).tolist()[3] - 0.3) < 1e-8

True

ones, zeros, empty  

* ones : 할당하고 초기화까지 한 것  
* empty : 할당하고 초기화를 하지 않고 임의로 값을 집어넣는다. 

In [59]:
a = np.zeros((5,),dtype=np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [60]:
b = np.ones((2,4),dtype=np.int8)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [61]:
np.empty((2,5))

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

특정 행렬의 shape를 가져와서 안에 다른 값 채우기  
* np.zeros_like()  
* np.ones_like()

In [62]:
a = np.arange(24).reshape(4,-1)
np.ones_like(a)    

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

* 단위행렬 : 대각 원소가 1인 정방행렬, 다른 행렬을 곱했을 때 다른행렬이 그대로 나온다.

In [66]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

np.eye(,) : 대각선이 1인 행렬

In [67]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [69]:
np.eye(N=3,M=5,k=-1) # 세번째 인수를 가지고 위치를 조절 할 수 있다. 

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [70]:
np.eye(N=3,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 7. Random Sampling

In [71]:
np.random.seed(2021)
np.random.uniform(0,1,10)

array([0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328,
       0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013])

In [75]:
#정규분포
np.random.normal(0,1,10).reshape(2,5)

array([[-2.79353057,  0.36164801,  0.24010758,  0.47781228,  0.20885194],
       [ 0.91791163, -1.41177784,  1.22423572, -0.54565772,  0.90674805]])

In [ ]:
이항분포, 포아송분포, t-분포, F-분포 모두 가능  
* 이항분포 : binominal  
* 포아송분포 : poisson  
* t분포 : standard_t  
* F분포 : f

In [79]:
#이항분포 - 동전 10개를 던져서 몇개의 앞면이 나오느냐.
np.random.binomial(100,0.5,10)  

array([42, 57, 48, 53, 51, 38, 47, 53, 52, 54])