In [1]:
import numpy as np

### 8. Operation

In [2]:
a = np.arange(1,11,dtype = np.float32)
a.sum()

55.0

In [5]:
b = np.arange(1,13,dtype=np.int8).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)

In [6]:
# 세로방향의 합
b.sum(axis=0)

array([15, 18, 21, 24])

In [7]:
# 가로방향의 합
b.sum(axis=1)

array([10, 26, 42])

In [8]:
# 평균 구하기
b.mean()

6.5

In [10]:
# 열 별 평균
b.mean(axis=0)

array([5., 6., 7., 8.])

In [11]:
# 행 별 평균
b.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [12]:
# 표준편차
b.std()

3.452052529534663

수학함수

In [13]:
X = np.arange(-1, 1.01,0.01)
X.size

201

* sigmoid 함수

In [18]:
Y = 1 / (1 + np.exp(-X))

* Concatenate  -
array 합치기 

In [24]:
a = np.arange(1,5).reshape(2,2)
b = np.array([[5,6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

* 전치행렬 transpose  
(1,2) 행렬이 (2,1)으로 바뀐다.

In [26]:
b.T

array([[5],
       [6]])

In [27]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [28]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

### 9. Array Operation

In [29]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [30]:
a / a

array([[1., 1.],
       [1., 1.]])

* dot product

In [32]:
a = np.arange(1,7).reshape(2,3)
a.dot(a.T)          # np.dot(a,a.T)

array([[14, 32],
       [32, 77]])

* Broadcasting  
차원이 다른 것끼리 연산을 할 경우  
단, shape이 비슷하긴 해야한다.

In [33]:
a + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [34]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [37]:
# 1차원 + 2차원 : 
a + np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])

### 10. Comparison

np.all() : 엘리먼트들이 모두 True(1)인지  
np.any() : 엘리먼트들 중에서 하나라도 True가 있는지 

In [39]:
a = np.arange(5)
np.all(a), np.any(a)

(False, True)

In [40]:
a > 2

array([False, False, False,  True,  True])

In [41]:
a[a > 2]

array([3, 4])

### 10-2. logical operation

In [43]:
a = np.arange(5)
b = np.logical_and(a > 0, a < 3)
b

array([False,  True,  True, False, False])

In [47]:
c = np.logical_not(b)

In [50]:
np.logical_or(b,c)      # 둘 중 하나라도 True면 True

array([ True,  True,  True,  True,  True])

In [49]:
np.logical_xor(b,c)     # 두 값이 다른 경우에 True가 나온다. 

array([ True,  True,  True,  True,  True])

In [51]:
a = np.arange(5)
np.where(a > 2)

(array([3, 4], dtype=int64),)

### 11. NaN, Inf  
* NaN (Not a Number) 
* Inf (Infinite)  
-> 이 경우 형식이 float여야 한다.

In [53]:
a = np.array([1,np.NaN,np.Inf],float)
a

array([ 1., nan, inf])

In [55]:
np.isnan(a), np.isfinite(a)     # 실수만 유한하고 나머지들은 유한하지 않다.

(array([False,  True, False]), array([ True, False, False]))

### 12. argmax, argmin  

가장 큰 값과 가장 작은 값의 색인 위치


In [62]:
a = np.arange(6)
np.argmax(a), np.argmin(a)

(5, 0)

In [58]:
b = np.arange(12).reshape(3,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
np.argmax(b,axis = 0)

array([2, 2, 2, 2], dtype=int64)

In [63]:
np.argmax(b,axis = 1)


array([3, 3, 3], dtype=int64)