In [1]:
import numpy as np

### 12.Boolean and Fancy Index  



In [3]:
np.random.seed(2021)
a = np.random.uniform(1,10,4)
a

array([6.45380451, 7.60032425, 2.25052441, 3.81405775])

In [4]:
a > 3

array([ True,  True, False,  True])

* Boolean indexing

In [5]:
# 3을 초과하는 엘리먼트만 가져오기 : 일종의 필터링
a[a>3]

array([6.45380451, 7.60032425, 3.81405775])

* Fancy index

In [6]:
a = np.arange(1,5) * 2
a

array([2, 4, 6, 8])

In [8]:
b = np.array([0,1,3,2,1,3])
a[b] # a[0], a[1], a[3] 이런 식으로 b가 인덱스가 되어서 a값을 가져온다.

array([2, 4, 8, 6, 4, 8])

In [9]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
b = np.array([0,0,1,1,0])
c = np.array([0,2,3,1,2])

a[b,c] # a[0,0], a[0,2] 이런 식으로 들어간다

array([0, 2, 7, 5, 2])