In [1]:
import numpy as np

### 1.넘파이를 이용한 행렬 만들기

In [2]:
a = np.arange(10,81,10).reshape(2,-1)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. m = np.array ~


In [3]:
m = np.arange(0,15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

1) 값 7을 인덱싱하라

In [4]:
m[1,2]

7

2) 값 14를 인덱싱하라

In [5]:
m[-1,-1]

14

3) \[6,7] 을 슬라이싱하라

In [6]:
m[1,1:3]

array([6, 7])

4) \[7,12] 를 슬라이싱

In [7]:
m[1:3,2]

array([ 7, 12])

5) 배열 \[\[3,4],\[8,9]]를 슬라이싱

In [8]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

### 3. 2번의 행렬 m을 벡터 f로 변환

In [9]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

1) 3의 배수를 찾아라

In [10]:
f[f % 3 == 0][1:]   #0은 배수가 아니므로 제외.

array([ 3,  6,  9, 12])

2) 4로 나누면 1이 남는 수를 찾아라. 

In [11]:
f[f % 4 == 1]

array([ 1,  5,  9, 13])

3) 3으로 나누면 나누어지고, 4로 나누면 1이 남는 수를 찾아라.

In [12]:
f[np.logical_and(f % 3== 0, f % 4 == 1)]

array([9])

### 4. 행렬 만들기

In [13]:
np.eye(5,5,dtype=int)*2 + np.eye(5,5,-1,dtype=int)*3 + np.eye(5,5,1,dtype=int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

### 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 \* 6 행렬만들기

In [14]:
m = np.random.uniform(0,10,(5,6))
m

array([[6.79326864e+00, 4.43624299e+00, 1.48047562e+00, 1.74220954e-01,
        5.52520352e-03, 7.34793747e+00],
       [2.80124361e+00, 7.28568609e+00, 5.89799075e+00, 8.90274082e+00,
        6.90716951e+00, 3.72225560e+00],
       [6.06523009e+00, 4.36331461e+00, 9.39528129e-01, 6.27884764e+00,
        3.20497197e+00, 8.01262062e+00],
       [9.40085102e-01, 9.49105782e+00, 9.68035518e+00, 6.49016966e+00,
        6.84199924e+00, 2.82233964e+00],
       [9.08901224e+00, 9.44604263e+00, 5.59642685e+00, 6.91806457e+00,
        2.24874980e+00, 1.88520728e-01]])

1) 전체의 최대값

In [15]:
np.max(m)

9.680355182785155

2)  각 행의 합

In [16]:
np.sum(m, axis=1)

array([20.23767088, 35.51708637, 28.86451306, 36.26600665, 33.48681682])

3) 각 행의 최댓값

In [17]:
np.max(m, axis=1)

array([7.34793747, 8.90274082, 8.01262062, 9.68035518, 9.44604263])

4) 각 열의 평균

In [18]:
np.mean(m, axis=0)

array([5.13776793, 7.00446883, 4.71895531, 5.75280873, 3.84168315,
       4.41873481])

5) 각 열의 최솟값

In [19]:
np.min(m, axis=0)

array([0.9400851 , 4.36331461, 0.93952813, 0.17422095, 0.0055252 ,
       0.18852073])

### 6. 영어 성적을 기준으로 각 열을 재정렬하기

In [20]:
score = np.array([[1,2,3,4],
[46,99,100,71],
[81,59,90,100]])

score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [21]:
a = score[:,score[1,:].argsort()]
a

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

### 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [22]:
die = np.random.randint(1,7,100)

In [23]:
die

array([5, 2, 3, 3, 4, 2, 1, 4, 6, 3, 4, 5, 2, 2, 6, 3, 1, 6, 5, 5, 5, 6,
       2, 1, 2, 4, 1, 6, 2, 5, 6, 4, 6, 3, 3, 3, 3, 1, 6, 6, 1, 2, 1, 6,
       1, 4, 4, 1, 3, 5, 4, 3, 3, 6, 4, 3, 3, 4, 2, 4, 4, 6, 6, 5, 4, 4,
       2, 6, 5, 6, 3, 6, 4, 3, 2, 3, 2, 3, 6, 6, 2, 6, 4, 4, 6, 2, 3, 3,
       3, 1, 6, 3, 4, 6, 4, 3, 1, 4, 6, 2])

In [24]:
die.mean()

3.7

### 8. 주식의 가격 = 10000원, 일간 수익률의 기댓값은 0%, 표준편차 1%일 때 250일간의 주기를 무작위로 생성

In [25]:
stock = (np.random.normal(0,1,250)/100)*10000 + 10000
stock

array([ 9999.10155205,  9864.09610744,  9960.97914436, 10195.97298313,
        9934.83183132,  9904.99944103,  9991.3259263 , 10154.45447529,
       10143.43765707,  9935.84017472, 10047.54337067,  9908.01138941,
       10064.43925717,  9788.99738312, 10140.77788197,  9909.68435296,
        9932.95364879, 10070.64561842, 10079.23629459,  9999.5386742 ,
       10002.53890286,  9950.87740935,  9996.05412106, 10030.72596969,
       10006.80338482, 10123.22149613, 10061.20417344, 10151.13823524,
        9895.33379158,  9998.02334294, 10170.54716909, 10101.18530531,
       10036.41476612, 10026.99237474, 10020.72268205,  9972.17275201,
        9972.96698895, 10030.19770855,  9936.393825  ,  9855.91402597,
       10111.90703703,  9971.1242099 , 10080.21760343, 10132.10069043,
       10095.92839638,  9852.30933978, 10009.0381546 , 10018.24293851,
        9964.77289237, 10103.12521486,  9921.55532256,  9942.68007672,
        9997.20632151,  9972.75942586, 10137.18968262, 10061.62373291,
      