In [6]:
import numpy as np

### 1.넘파이를 이용한 행렬 만들기

In [7]:
a = np.arange(10,81,10).reshape(2,-1)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. m = np.array ~


In [8]:
m = np.arange(0,15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

1) 값 7을 인덱싱하라

In [9]:
m[1,2]

7

2) 값 14를 인덱싱하라

In [10]:
m[-1,-1]

14

3) \[6,7] 을 슬라이싱하라

In [11]:
m[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

4) \[7,12] 를 슬라이싱

In [12]:
m[1:3,2]

array([ 7, 12])

5) 배열 \[\[3,4],\[8,9]]를 슬라이싱

In [13]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

### 3. 2번의 행렬 m을 벡터 f로 변환

In [14]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

1) 3의 배수를 찾아라

In [15]:
f[f % 3 == 0][1:]   #0은 배수가 아니므로 제외.

array([ 3,  6,  9, 12])

2) 4로 나누면 1이 남는 수를 찾아라. 

In [16]:
f[f % 4 == 1]

array([ 1,  5,  9, 13])

3) 3으로 나누면 나누어지고, 4로 나누면 1이 남는 수를 찾아라.

In [17]:
f[np.logical_and(f % 3== 0, f % 4 == 1)]

array([9])

### 4. 행렬 만들기

In [18]:
np.eye(5,5,dtype=int)*2 + np.eye(5,5,-1,dtype=int)*3 + np.eye(5,5,1,dtype=int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

### 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 \* 6 행렬만들기

In [14]:
np.random.seed(2021)
m = np.random.uniform(0,10,(5,6))
m

array([[6.79326864e+00, 4.43624299e+00, 1.48047562e+00, 1.74220954e-01,
        5.52520352e-03, 7.34793747e+00],
       [2.80124361e+00, 7.28568609e+00, 5.89799075e+00, 8.90274082e+00,
        6.90716951e+00, 3.72225560e+00],
       [6.06523009e+00, 4.36331461e+00, 9.39528129e-01, 6.27884764e+00,
        3.20497197e+00, 8.01262062e+00],
       [9.40085102e-01, 9.49105782e+00, 9.68035518e+00, 6.49016966e+00,
        6.84199924e+00, 2.82233964e+00],
       [9.08901224e+00, 9.44604263e+00, 5.59642685e+00, 6.91806457e+00,
        2.24874980e+00, 1.88520728e-01]])

1) 전체의 최대값

In [20]:
np.max(m)

True

2)  각 행의 합

In [16]:
np.sum(m, axis=1)

array([20.23767088, 35.51708637, 28.86451306, 36.26600665, 33.48681682])

3) 각 행의 최댓값

In [17]:
np.max(m, axis=1)

array([7.34793747, 8.90274082, 8.01262062, 9.68035518, 9.44604263])

4) 각 열의 평균

In [18]:
np.mean(m, axis=0)

array([5.13776793, 7.00446883, 4.71895531, 5.75280873, 3.84168315,
       4.41873481])

5) 각 열의 최솟값

In [19]:
np.min(m, axis=0)

array([0.9400851 , 4.36331461, 0.93952813, 0.17422095, 0.0055252 ,
       0.18852073])

### 6. 영어 성적을 기준으로 각 열을 재정렬하기

In [23]:
score = np.array([[1,2,3,4],
[46,99,100,71],
[81,59,90,100]])

score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

argsort() : 정렬하는 인덱스의 어레이

In [27]:
a = score[:,score[1,:].argsort()]
a

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

### 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [22]:
np.random.seed(2021)
die = np.random.randint(1,7,100)

In [23]:
die

array([5, 2, 3, 3, 4, 2, 1, 4, 6, 3, 4, 5, 2, 2, 6, 3, 1, 6, 5, 5, 5, 6,
       2, 1, 2, 4, 1, 6, 2, 5, 6, 4, 6, 3, 3, 3, 3, 1, 6, 6, 1, 2, 1, 6,
       1, 4, 4, 1, 3, 5, 4, 3, 3, 6, 4, 3, 3, 4, 2, 4, 4, 6, 6, 5, 4, 4,
       2, 6, 5, 6, 3, 6, 4, 3, 2, 3, 2, 3, 6, 6, 2, 6, 4, 4, 6, 2, 3, 3,
       3, 1, 6, 3, 4, 6, 4, 3, 1, 4, 6, 2])

In [24]:
die.mean()

3.7

### 8. 주식의 가격 = 10000원, 일간 수익률의 기댓값은 0%, 표준편차 1%일 때 250일간의 주기를 무작위로 생성

In [15]:
stock = [10000]
np.random.seed(2021)
for i in range(250):
    rate = np.random.normal(0,1,1)/100
    price = int(np.round(stock[-1]*rate + stock[-1],0))
    stock.append(price)
    
del stock[0]
print(stock)

[10135, 10212, 10184, 10220, 10414, 10478, 10480, 10511, 10647, 10594, 10626, 10677, 10656, 10610, 10439, 10264, 10465, 10400, 10434, 10478, 10392, 10526, 10604, 10498, 10121, 10089, 10131, 10268, 10308, 10255, 10146, 10230, 10212, 10295, 10390, 10337, 10436, 10360, 10255, 10218, 10252, 10068, 10065, 10171, 10217, 10138, 10041, 9975, 9921, 9824, 9846, 9794, 9844, 9877, 10048, 10093, 10191, 10279, 10455, 10583, 10694, 10777, 10608, 10523, 10738, 10578, 10415, 10469, 10243, 10304, 10368, 10437, 10411, 10479, 10501, 10622, 10585, 10565, 10622, 10711, 10781, 10770, 10832, 10906, 10865, 10813, 10789, 10514, 10597, 10914, 10995, 10826, 10598, 10489, 10470, 10494, 10570, 10664, 10622, 10471, 10610, 10764, 10805, 10810, 10863, 10750, 10542, 10684, 10712, 10636, 10489, 10395, 10491, 10487, 10613, 10582, 10841, 10844, 10812, 10683, 10448, 10475, 10440, 10359, 10346, 10225, 10165, 10293, 10523, 10566, 10553, 10544, 10466, 10594, 10387, 10429, 10401, 10515, 10449, 10498, 10519, 10607, 10630, 10661